#
# Reusable workflow which verifies the project builds successfully on multiple Java versions.
#
# On success, its Dependency Snapshot is submitted.
#
# Permissions required:
# - contents: write
# - security-events: write
#
name: Build

on:
  workflow_call:
    inputs:
      java_matrix:
        description: '(JSON array) Java versions'
        type: string
        default: "[ '17', '21', '25' ]"
        required: false

jobs:
  build:
    name: Java ${{ matrix.java }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ${{ fromJson(inputs.java_matrix) }}
      fail-fast: false
    env:
      JAVA_DISTRO: 'temurin'

    #
    # NOTE
    #
    # The build is based on two JDKs:
    #   - Tool JDK: from `.tool-versions` file
    #   - Target JDK: from java matrix
    # Those JDKs are applied to three levels:
    #   1. Maven execution: Tool JDK
    #   2. Java compiler: Tool JDK, unless Target JDK is newer (Tool JDK represents the minimum
    #      requirement to run the toolchain on any environment (development or CI), so it is applied
    #      unless the source code requires a newer version)
    #   3. Java source code: Target JDK
    #
    # |----------------------------------------------------------------------------------------------|
    # |                       |           JDK             |                       |                  |
    # |         Level         |---------------------------|    System property    |  MANIFEST entry  |
    # |                       |  Tool JDK  |  Target JDK  |                       |                  |
    # |----------------------------------------------------------------------------------------------|
    # |  1. Maven execution   |      X     |              |  (none: default JDK)  |  Tool-Jdk-Spec   |
    # |----------------------------------------------------------------------------------------------|
    # |  2. Java compiler     |        (newer one)        |  build.jdk            |  Build-Jdk-Spec  |
    # |----------------------------------------------------------------------------------------------|
    # |  3. Java source code  |            |       X      |  target.jdk           |  Java-Version    |
    # |----------------------------------------------------------------------------------------------|
    #

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Resolve Tool JDK
        id: tool-versions
        uses: marocchino/tool-versions-action@4219f2e6bfdb4cce482b78f71ad9663e64f4d247 # v2.0.0

      - name: Set up Target JDK
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ env.JAVA_DISTRO }}
          cache: maven

      - name: Set up Tool JDK
        # IMPORTANT: Tool JDK MUST be the last to set up in order to make it the default one and run
        #            Maven.
        uses: actions/setup-java@v5
        with:
          java-version: ${{ steps.tool-versions.outputs.java }}
          distribution: ${{ env.JAVA_DISTRO }}

      - name: Set up Java environment variables
        env:
          TARGET_JDK: ${{ matrix.java }}
          TOOL_JDK: ${{ steps.tool-versions.outputs.java }}
        run: |
          # Export BUILD_JDK!
          if printf '%s\n' "$TOOL_JDK" "$TARGET_JDK" | sort -V -C; then
            readonly build_jdk=$TARGET_JDK
          else
            readonly build_jdk=$TOOL_JDK
          fi
          echo "BUILD_JDK=$build_jdk" >> $GITHUB_ENV

          # Export TARGET_JDK!
          echo "TARGET_JDK=$TARGET_JDK" >> $GITHUB_ENV

          # Export TARGET_JDK_HOME!
          readonly target_major=$(echo "$TARGET_JDK" | cut -d'.' -f1)
          readonly target_jdk_home_varname="JAVA_HOME_${target_major}_${{ runner.arch }}"
          readonly target_jdk_home="${!target_jdk_home_varname}"
          if [ -z "$target_jdk_home" ]; then
            echo "Error: $target_jdk_home_varname not set"
            exit 1
          fi
          echo "TARGET_JDK_HOME=$target_jdk_home" >> $GITHUB_ENV

          # Export DEFAULT_TARGET_JDK!
          readonly default_target_jdk=$(./mvnw help:evaluate -Dexpression=target.jdk -DforceStdout -q)
          if [ -z "$default_target_jdk" ]; then
            echo "Error: DEFAULT_TARGET_JDK not set (target.jdk property in POM undefined)"
            exit 1
          fi
          echo "DEFAULT_TARGET_JDK=$default_target_jdk" >> $GITHUB_ENV

      - name: Build with Maven
        run: |
          echo "BUILD_JDK: $BUILD_JDK" >&2
          echo "DEFAULT_TARGET_JDK: $DEFAULT_TARGET_JDK" >&2
          echo "TARGET_JDK: $TARGET_JDK" >&2
          echo "TARGET_JDK_HOME: $TARGET_JDK_HOME" >&2

          # If Target JDK is different from the predefined one, disable lint failure, so warnings
          # are emitted without disrupting the build (conversely, if Target JDK corresponds to the
          # predefined one, fail on lint warnings, as they should have already been fixed on
          # development)!
          if [ "$TARGET_JDK" != "$DEFAULT_TARGET_JDK" ]; then
            lenient_lint_option=-Dlint.lenient
          fi

          ./mvnw verify \
              -Dtarget.jdk=$TARGET_JDK \
              -Dtarget.jdk.home="$TARGET_JDK_HOME" \
              -Dbuild.jdk=$BUILD_JDK \
              $lenient_lint_option \
              --batch-mode --errors

  submit-dependency-snapshot:
    name: Submit Dependency Snapshot
    runs-on: ubuntu-latest
    needs: build
    # Run only on pushes to main after the entire matrix build succeeded.
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.build.result == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Submit Dependency Snapshot
        # NOTE: Automatic dependency submission (see
        #       <https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/configuring-automatic-dependency-submission-for-your-repository>)
        #       didn't work, so manual submission (aka user submission) was integrated here, running
        #       on push events affecting the main branch only.
        uses: advanced-security/maven-dependency-submission-action@v5
