#
# Reusable workflow which publishes a release version to Maven Central repository.
#
# Permissions required:
# - contents: write
#
# Maintainers' post-activities:
# 1. the RELEASE COMPONENTS are uploaded to Maven Central for validation: verify and publish them.
# 2. the RELEASE BRANCH is automatically created to include release preparation commits: verify and
#    merge it to `main`, and finally discard it.
# 3. the GITHUB RELEASE is created as draft: verify and publish it.
#
name: Release

on:
  workflow_call:
    inputs:
      repo_title:
        description: 'Repository name (e.g., pdfClown Common)'
        type: string
        required: true
      revision:
        description: '(SemVer2) Version to release'
        type: string
        required: true
      scm_startpoint:
        description: 'Release branch start point (by default, main HEAD)'
        type: string
        required: false

jobs:
  release:
    name: Publish release
    runs-on: ubuntu-latest
    env:
      COMMITIZEN_VERSION: '4.10.0'
      RELEASE_TAG: v${{ inputs.revision }}
      RELEASE_VERSION: ${{ inputs.revision }}

    #
    # NOTE
    #
    # The build is based on two JDKs:
    #   - Tool JDK: from `.tool-versions` file
    #   - Target JDK: from Maven POM
    # Those JDKs are applied to three levels:
    #   1. Maven execution: Tool JDK
    #   2. Java compiler: Tool JDK (`build.jdk` system property is expected to be set the same as in
    #      `.tool-versions` file)
    #   3. Java source code: Target JDK
    #
    # |----------------------------------------------------------------------------------------------|
    # |                       |           JDK             |                       |                  |
    # |         Level         |---------------------------|    System property    |  MANIFEST entry  |
    # |                       |  Tool JDK  |  Target JDK  |                       |                  |
    # |----------------------------------------------------------------------------------------------|
    # |  1. Maven execution   |      X     |              |  (none: default JDK)  |  Tool-Jdk-Spec   |
    # |----------------------------------------------------------------------------------------------|
    # |  2. Java compiler     |      X     |              |  (none: default JDK)  |  Build-Jdk-Spec  |
    # |----------------------------------------------------------------------------------------------|
    # |  3. Java source code  |            |       X      |  target.jdk           |  Java-Version    |
    # |----------------------------------------------------------------------------------------------|
    #

    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "commitizen==${{ env.COMMITIZEN_VERSION }}"

      - name: Set up Java
        uses: pdfclown/.github/.github/actions/setup-java-publish
        with:
          gpg_signing_key: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Install local Java dependencies (pdfclown-common)
        run: |
          # NOTE: The release executor requires pdfclown-common-*; if such dependencies are local,
          #       they have to be explicitly installed before executing the release (they cannot be
          #       included in the automated release process because of cyclic reference issues).
          if [ -d pdfclown-common-build ]; then
            ./mvnw install -Pfast+ -DskipLint --batch-mode --errors
          fi

      - name: Configure SCM
        run: |
          git config user.name "pdfClown.org CI"
          git config user.email "stechio@users.noreply.github.com"

      - name: Publish with Maven
        env:
          MAVEN_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SIGNING_KEY_PASSPHRASE }}
        run: |
          echo "TARGET_JDK: $TARGET_JDK" >&2
          echo "TARGET_JDK_HOME: $TARGET_JDK_HOME" >&2

          # NOTE:
          # - no need to set `target.jdk` property, as project's default corresponds to Target JDK
          # - no need to set `build.jdk` property, as project's default corresponds to Tool JDK
          ./mvnw initialize -Prelease \
              -Drelease.version=$RELEASE_VERSION \
              -Drelease.startpoint=${{ inputs.scm_startpoint }} \
              -Dtarget.jdk.home="$TARGET_JDK_HOME" \
              -N --batch-mode --errors

      - name: Create GitHub Release (draft)
        # NOTE: Generated notes are configured via `.github/release.yml`.
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "$RELEASE_TAG" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${{ inputs.repo_title }} $RELEASE_VERSION" \
              --generate-notes \
              --draft
